version: "3.8"

services:
  budgetdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: budgetdb
    ports:
      - "5432:5432"
    volumes:
      - budgetdb_data:/var/lib/postgresql/data

volumes:
  budgetdb_data: {}
